### ISSUE TITLE
Files in the bin

### ISSUE THREAD

**Issue by javiavid** [IgorRidanovic/DaVinciResolve-PrintBins#1]
When creating the list of bins, does it also export the list of files inside those bins?

**Comment by IgorRidanovic** [comment]
It does not list the media pool items inside the bins.

**Comment by javiavid** [comment]
Is there a way to do this with a script, plugin or natively?

**Comment by IgorRidanovic** [comment]
Yes, calling GetClipList() on a bin object will return a list of media pool items residing in that bin. I think this list will contain everything in the bin including things like timelines, titles, etc. You'd then have to filter out the clips if the clips are the only thing you're looking for. There is no built-in method for this filtering, but you can discriminate the list items based on their properties.

**Comment by javiavid** [comment]
Thanks for the reply

I am not have knowledge of python, but my idea was to be able to get that list of files inside a bin, then with an external script to synchronize the bins with the folders on the disk.  I think you could get something similar to a DAM MAM integrated into davinci and it could be very interesting.

**Comment by IgorRidanovic** [comment]
If I understand correctly the idea is for a Resolve bin to reflect the contents of a file system directory at all times. That is possible except that the API does not support media pool item deletion. Any files removed from the file system would still have their corresponding clips in the bin. Of course, the media would appear offline.

**Comment by javiavid** [comment]
Yes, that's the idea. It's not ideal, but one option would be to delete the bin and re-import it with the option to create bins from media storage.
I think that it is not a system for a constant update in a simple and fast way, but having this possibility to do it at least once a day, could be interesting.

One way to preserve the metadata is to export it and import it again when importing the media.

I know that there are several steps and I don't know which of them can be automated, but if it is obtained in an external file where each clip is inside davinci, it may be a step to achieve it.
